name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --plugin-search-dir . --check .

      - name: Run ESLint
        run: npx eslint .

  lighthouseci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: npm run build
        env:
          SENDGRID_API_KEY: SG_TEST
          EMAIL: TEST
      - run: |
          lhci autorun \
            --collect.startServerCommand="npm run preview" \
            --collect.startServerReadyPattern="Local" \
            --collect.url=http://localhost:4173 \
            --collect.url=http://localhost:4173/teams \
            --collect.url=http://localhost:4173/execs \
            --collect.url=http://localhost:4173/contact \
            --collect.settings.preset=desktop \
            --assert.assertions.categories:performance=warn \
            --assert.assertions.categories:accessibility=warn \
            --assert.assertions.categories:best-practices=warn \
            --assert.assertions.categories:seo=warn \
            --assert.assertions.categories:pwa=off \
            --upload.target="temporary-public-storage"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: .lighthouseci
