name: ESLint & Prettier

on:
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']

jobs:
  lint:
    name: Run code scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@^8.34.0
          npm install eslint-config-prettier@^8.6.0
          npm install eslint-plugin-svelte3@^4.0.0
          npm install @typescript-eslint/eslint-plugin@^5.53.0
          npm install @typescript-eslint/parser@^5.53.0

      - name: Install Prettier
        run: |
          npm install prettier@^2.8.4
          npm install prettier-plugin-svelte@^2.9.0

      - name: Run Prettier
        run: npx prettier --plugin-search-dir . --check .

      - name: Run ESLint
        run: npx eslint .
