name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Prettier
        run: |
          npm install \
            prettier@^2.8.4 \
            prettier-plugin-svelte@^2.9.0

      - name: Install ESLint
        run: |
          npm install eslint@^8.34.0
            eslint-config-prettier@^8.6.0 \
            eslint-plugin-svelte3@^4.0.0 \
            @typescript-eslint/eslint-plugin@^5.53.0 \
            @typescript-eslint/parser@^5.53.0

      - name: Run Prettier
        run: npx prettier --plugin-search-dir . --check .

      - name: Run ESLint
        run: npx eslint .
